baseURL: http://sqldefender.com/
languageCode: en-us
title: SQL Defender
theme: minimal
menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1
    # - identifier: docs
    #   name: Documentation
    #   title: Documentation
    #   url: /documentation/
    #   weight: 2
    - identifier: faq
      name: FAQ
      title: Frequently Asked Questions
      url: /faq/
      weight: 3
    - identifier: contact
      name: Contact
      title: Contact Us
      url: "#contact"
      weight: 4